### ISSUE TITLE
메모가 한꺼번에 삭제됐어요

### ISSUE THREAD

**Issue by nonohako** [green1052/DCRefresher-Reborn#1]
메모에서 하나를 삭제하면 전체가 다 삭제되는 버그가 있습니다.
메모들이 다 날아갔어요..

**Comment by green1052** [comment]
사용하시는 브라우저와 리프레셔 버전을 알려주실 수 있나요?

**Comment by green1052** [comment]
테스트 해보니깐 날라가네요...

**Comment by green1052** [comment]
2.0.3 릴리즈에서 수정됐습니다.
