### ISSUE TITLE
디시콘을 연속으로 사용할시 강제로 중복선택이됨

### ISSUE THREAD

**Issue by tangbat** [green1052/DCRefresher-Reborn#116]
댓글로 디시콘 연속으로 사용시 횟수 제한 없이 같은 디시콘이 선택됨.

**Comment by green1052** [comment]
안녕하세요 혹시 리프레셔의 버전과 어디서 디시콘을 작성하셨는지 알 수 있을까요?
미리보기 화면에서는 현재 디시콘 작성 기능을 지원하지 않고 있습니다.

**Comment by tangbat** [comment]
버전:1.6.4
아무 갤러리에 미리보기를 통하지않고 게시글에 직접 댓글로 디시콘을 달때 일어납니다.
리프레셔를 삭제 했을때는 해당 현상이 일어나지 않는걸 확인 했습니다.

**Comment by green1052** [comment]
브라우저는 어떤걸 사용하시나요?

**Comment by tangbat** [comment]
업데이트가 있는걸 확인하여 버전 1.6.6을 설치하여 다시 테스트 해봤으나 여전히 같은 현상을 경험 했습니다.
브라우저는 크롬을 사용중입니다.

**Comment by green1052** [comment]
확인해보겠습니다

**Comment by green1052** [comment]
테스트 게시글: https://gall.dcinside.com/board/view/?id=programming&no=2122599&page=1

**Comment by tangbat** [comment]
해당 확장 프로그램을 사용한적이 없는 컴퓨터로 테스트를 해봤습니다.
설치 직후 해당 현상을 재현을 할수 없었고, 설정->일반->레이아웃 수정에 있는 모든 옵션들을 활성화하고 다시 테스트 했으나 재현
할수가 없었습니다.
고급 설정하에 no-cache 헤더 추가와 방문 링크 색상 지정 비활성화 옵션을 활성화 했더니 해당 현상을 다시 확인할수가 있었으며
이후 활성화한 모든 설정 비활성화와 확장 프로그램 재설치 그리고 쿠키 삭제를 해보았으나 해당 현상을 확인할수가 있었습니다.
여전히 확장 프로그램을 삭제를 하면 디시콘이 문제 없이 적용됩니다.

2022년 5월 5일 (목) 오전 7:29, green1052 ***@***.***>님이 작성:

**Comment by green1052** [comment]
방문 링크 색상 지정 비활성화, no-cache 헤더 
설정을 키고 난 뒤에 디시콘 문제가 발생하고

이게 발생하고 나면 쿠키를 지우고 확장 프로그램을 재설치해도 문제가 또 발생한다는 뜻인가요?

**Comment by tangbat** [comment]
3번째 환경에서 테스트 결과 확장 프로그램의 문제가 아닌 서버상의 문제인것 같습니다.
실례했습니다.

2022년 5월 5일 (목) 오전 9:32, green1052 ***@***.***>님이 작성:

**Comment by green1052** [comment]
확인했습니다, 그럼 이슈는 닫겠습니다.
