### ISSUE TITLE
세로 화면에서 특정 위치의 글 클릭이 안되는 증상

### ISSUE THREAD

**Issue by duck0234** [green1052/DCRefresher-Reborn#117]
**버그 설명**
컴팩트 모드를 켜고 디시를 세로 화면에서 사용하면 글 클릭이 안되는 증상이 있습니다.
화면 배율이 100%일때만 버그가 생깁니다. (확대하면 클릭 가능, 축소하거나 100%일때 버그 발생)
클릭 안되는 영역에 있는 글은 마우스를 올려도 변화가 없고, 클릭 안되는 영역에 있더라도 제목 길이가 길어서 밖으로 나오는 글은 클릭 가능

**재현 방법**
컴팩트 모드 ON
브라우저 내 설정에서 화면 확대 100%
페이지 로딩 완료되면 화면 특정 위치의 글이 클릭이 안됨(로딩 중에는 눌립니다)

**예상 동작**

**스크린샷**
![123](https://github.com/user-attachments/assets/bf7c77f4-b494-435f-8e36-38cbb6362e75)

이 영역에 마우스를 올리면 클릭이 안됩니다

**환경:**
 - OS: 윈도우 11
 - 브라우저: 크롬, 엣지
 - 버전: 크롬 127.0.6533.73, 엣지 127.0.2651.74

**추가 설명**

**Comment by green1052** [comment]
재현 불가능합니다

**Comment by duck0234** [comment]
> 재현 불가능합니다

해결했습니다. 광고 차단을 끄니 해당 위치에 광고가 뜨는데, 광고 차단을 켜면 투명한 창만 남아 그 부분을 가려서 클릭이 안되는 거였네요;;
