### ISSUE TITLE
미리보기 기능 건의

### ISSUE THREAD

**Issue by ELG66** [green1052/DCRefresher-Reborn#13]
본문에 들어간 상태에서는 쉬프트+엔터로 댓글 줄바꿈이 가능함.
하지만 단순히 미리보기에서는 댓글에 줄바꾸는게 불가능함. 엔터를 누를시 등록이 되고, 쉬프트나 컨트롤을 더해서 눌러도 그대로 등록됨. 해당 기능 수정 요망합니다.

**Comment by green1052** [comment]
예전 버전에서는 가능했지만 [해당 커밋](https://github.com/green1052/DCRefresher-Reborn/commit/298ecb11af64283d26086e28ce4f09da3f81cd07)에서 삭제해 댓글 여러줄 작성 기능은 지원하지 않고 있습니다.

다시 롤백하도록 하겠습니다.

**Comment by green1052** [comment]
추가됐습니다.

**Comment by green1052** [comment]
[3.8.0](https://github.com/green1052/DCRefresher-Reborn/releases/tag/3.8.0)에서 반영됐습니다.
