### ISSUE TITLE
다크모드시 커서 올릴 때 글의 텍스트 시인성

### ISSUE THREAD

**Issue by DogPam** [green1052/DCRefresher-Reborn#139]
**버그 설명**
갤 자체 우측상단 야간모드 실행 시 글에 마우스 올려둘 때 나오는 글 내용의 텍스트 색이 그레이라 너무 시인성이 안보임
검정색으로 수정 바람

**재현 방법**
갤 자체 다크모드인 우측상단 야간모드 실행-아무글이나 커서 올려서 글 내용 뜨게함 - 텍스트가 그레이로 잘 안보임

**예상 동작**

**스크린샷**
![캡처](https://github.com/user-attachments/assets/f6e69577-2d0c-4f68-925d-56ab5976c610)

**환경:**
 - OS: 윈도우10
 - 브라우저: 크롬
 - 버전: 3.11.10

**추가 설명**

**Comment by green1052** [comment]
디시인사이드 자체 다크모드와 리프레셔는 서로 호환되지 않습니다.
