### ISSUE TITLE
마이너 갤러리 관리내역 페이지 넘김 버그

### ISSUE THREAD

**Issue by gnollwieldinghalberd** [green1052/DCRefresher-Reborn#15]
갤러리 관리내역이 오픈된 마이너 갤러리에서 관리내역 창을 연 뒤 페이지를 넘기면, 관리내역 대신 갤러리 일반글 페이지가 넘어가서 관리내역 뒤쪽 페이지를 읽을수가 없읍니다..

**Comment by green1052** [comment]
확인해보겠습니다

**Comment by gnollwieldinghalberd** [comment]
가끔 정상적으로 관리내역 페이지가 넘어가는 경우도 있는데 일반글 페이지 스크롤 한번 내리면 다시 고장나는 것 같네요

**Comment by green1052** [comment]
수정됐습니다, `인페이지 페이지 전환` 설정 문제이니
적용 전 까지는 해당 옵션을 끄시면 됩니다.
