### ISSUE TITLE
글쓰기 개선 - 이미지 업로드 기능 미작동

### ISSUE THREAD

**Issue by Gnbrkm41** [green1052/DCRefresher-Reborn#17]
![image](https://user-images.githubusercontent.com/42944058/217448448-f53bb9de-8c79-4f76-acf1-c468feb0bb34.png)

본문 영역에 Ctrl+V로 이미지 붙여넣을 시 다음과 같이 본문 길이 제한만 뜨고 작동하지 않습니다.

**Comment by green1052** [comment]
이벤트리스너가 등록되지 않아 발생하는 문제입니다.
F12를 누르시고 console 탭으로 이동해 빨간색으로 보이는 문자를 보내주세요

**Comment by Gnbrkm41** [comment]
![image](https://user-images.githubusercontent.com/42944058/217611149-619a6ffe-28a6-4ece-aeab-195d0cc7ba07.png)
별도로 exception log는 보이지 않습니다

**Comment by green1052** [comment]
세팅 한번 껏다 켜봐주실 수 있나요?

**Comment by Gnbrkm41** [comment]
정확히 어디에서 무슨 설정을 껐다 켜보라는 말씀이실까요?

**Comment by Gnbrkm41** [comment]
자짤 설정 껐다 켜도 마찬가지인 것 같습니다

**Comment by green1052** [comment]
자짤 설정말고

```이미지 업로드``` 설정이요

**Comment by green1052** [comment]
아니면 그냥 설정 부분 사진을 보내주세요

**Comment by Gnbrkm41** [comment]
말을 실수했습니다. 이미지 업로드 설정 껐다 켜도 마찬가지입니다.

![image](https://user-images.githubusercontent.com/42944058/217626920-510a30a6-239d-4cb6-ae00-4721a4aa85cd.png)
![image](https://user-images.githubusercontent.com/42944058/217626988-2e8e506b-4235-4c8b-959f-e7678197d2b7.png)

방금 업데이트된 한 글자 제목 기능은 정상 작동합니다.

**Comment by green1052** [comment]
브라우저 뭐쓰시나요?

**Comment by Gnbrkm41** [comment]
Microsoft Edge 111.0.1660.6 (Official build) dev (64-bit)

**Comment by Gnbrkm41** [comment]
![image](https://user-images.githubusercontent.com/42944058/217724761-3782e0d8-734d-443d-9491-ab36a72312f5.png)
🤨

**Comment by Gnbrkm41** [comment]
디시 에디터가 아직 로딩이 덜 된 상태에서 inject되는게 아닐까 싶기도 합니다. 

![image](https://user-images.githubusercontent.com/42944058/217725835-42a05991-61f8-47c4-8713-301e7c2e7a08.png)

![image](https://user-images.githubusercontent.com/42944058/217725821-e05253c3-9802-40b9-bd6d-ecc8e885be84.png)

로드 시 확장 프로그램 코드 내부에 breakpoint 걸고 확인하면 iframe body 내 아무것도 존재하지 않습니다.

![image](https://user-images.githubusercontent.com/42944058/217726135-7d1f3e2c-8c1f-4b83-a8b1-de0593731cb3.png)

로드 된 후에는 tx-content-container 정상 존재합니다.

**Comment by Gnbrkm41** [comment]
Still no workie :-(

![image](https://user-images.githubusercontent.com/42944058/218053997-3163f17c-edd6-4675-8444-7f44e82ad953.png)
![image](https://user-images.githubusercontent.com/42944058/218054281-42622c9a-8f42-4437-8930-ebb0faadcf59.png)
console.log 호출 2개정도 추가하고 봤는데, 필터는 정상 추가되는데 callback에 추가한 log 함수는 호출되지 않음

**Comment by green1052** [comment]
외않되

**Comment by Gnbrkm41** [comment]
Reproducible on Google Chrome 111.0.5563.19 (Official build) dev (64-bit) (cohort: Dev) w/ 디시리프레셔 3.9.2

**Comment by Gnbrkm41** [comment]
Not reproducible on Mozilla Firefox 110.0b9 (Dev)

**Comment by Gnbrkm41** [comment]
Also not reproducible on Microsoft Edge 110.0.1587.41 (Official build) (64-bit)

**Comment by green1052** [comment]
크롬에서도 재현이 안됩니다.

**Comment by Gnbrkm41** [comment]
크로미엄 계열 브라우저 개발자 프리뷰에서만 문제가 발생하는 것 같습니다. 브라우저 버그일 가능성도 없잖아 있긴 한데... 잘 모르겠습니다. 좀 더 코드 뜯어보고 확인해봐야 할 듯.

**Comment by green1052** [comment]
일단 한번 DOM 로드 기다리게 설정했는데
수정된 파일 드려볼게요

**Comment by green1052** [comment]
[dist.zip](https://github.com/green1052/DCRefresher-Reborn/files/10708246/dist.zip)

**Comment by Gnbrkm41** [comment]
받았습니다. 좀 있다가 확인해보도록 하겠습니다.

**Comment by green1052** [comment]
???

**Comment by Gnbrkm41** [comment]
방금 확인했는데 동일합니다. 
![image](https://user-images.githubusercontent.com/42944058/218150110-e51a30ff-c7e7-49a3-a481-9b5497da86e2.png)
filter.add line까지는 breakpoint 걸면 제대로 중단되지만(첫번째 breakpoint) callback 함수 내부에선 중단되지 않고 (두번째 breakpoint) 로그 창에도 별도 메시지 없이 넘어갑니다.

**Comment by green1052** [comment]
진짜 모르겠네요

**Comment by green1052** [comment]
혹시 다른 기능 테스트 좀 부탁 드릴 수 있을까요

**Comment by green1052** [comment]
혹시 다른 확장 프로그램 끄시고 다시 시도 해주실 수 있나요?

**Comment by Gnbrkm41** [comment]
> 다른 확장 프로그램 끄시고 다시 시도 해주실 수 있나요?

다른 확장 프로그램 꺼도 동일 증상입니다.

> 다른 기능 테스트

한 글자 제목 작성 작동 안합니다. 예전엔 작동했는데 지금은 안 되는 듯.

**Comment by green1052** [comment]
업로드 기능은 
다른 분한테 edge 환경에서 테스트 부탁드렸는데 된다고 하시네요

한 글자 제목은 안된다고 하시고요

**Comment by Gnbrkm41** [comment]
다른 PC 엣지 개발자 버전에서 한번 더 테스트 해보고 알려드리겠습니다

**Comment by green1052** [comment]
아마 한 글자 제목 안되는건 사이트 로딩 돌아가고 있을때
등록 누르셔서 그런거 같은데요?

![image](https://user-images.githubusercontent.com/34261355/218501995-097c8571-feab-4a03-9cf8-1bd779a08cbe.png)

**Comment by green1052** [comment]
고쳤읍니다...

**Comment by green1052** [comment]
[dist.zip](https://github.com/green1052/DCRefresher-Reborn/files/11790703/dist.zip)

**Comment by green1052** [comment]
한번 테스트 해보시고 알려주세요
