### ISSUE TITLE
툴팁 미리보기때 전부 보는 옵션은 없을까요?

### ISSUE THREAD

**Issue by Miksya** [green1052/DCRefresher-Reborn#2]
툴팁 미리보기로 볼 때 자짤로 내용이 다 가려지는 경우가 있는데 글 내용을 전부 보는 옵션이 있으면 좋을 것 같아요

**Comment by green1052** [comment]
미리보기 화면에서 이미지를 숨기는 옵션을 추가하는게
낫다 생각하는데 어떠신가요?

내용 전체를 보이게 하면 미리보기라는 컨셉에 맞지 않는거 같네요

**Comment by Miksya** [comment]
오... 그것도 좋을 것 같네요 
고해상도 유저의 경우 세로에 좀 더 여유가 있으니 추가로
미리 보여주는 내용이 좀 더 늘어나는 옵션이 있으면 좋을 것 같아요

**Comment by green1052** [comment]
[3.0.0](https://github.com/green1052/DCRefresher-Reborn/releases/tag/3.0.0)에서 추가됐습니다.

manifest 수정해서 크롬 웹 스토어에도 신청 했읍니다..
