### ISSUE TITLE
3.9.0 업데이트 후 새로고침시 다크모드 해제됨

### ISSUE THREAD

**Issue by kjma8y** [green1052/DCRefresher-Reborn#20]
릴리즈에는 코드 정돈이라고만 써있어서 방금 업뎃하고 다른거는 확인을 못하긴 했는데 새로고침하거나 글쓰기하면 다크모드해놓은게 풀리네요

**Comment by kjma8y** [comment]
아 그리고 브라우저는 크롬이랑 웨일에서 다크모드 해제되는거 확인함

**Comment by green1052** [comment]
related #16

**Comment by green1052** [comment]
![Screenshot_20230209_033950_Bromite](https://user-images.githubusercontent.com/34261355/217622300-a589e958-359c-4814-a376-cc0e022bee68.png)

변경점은 사진에 Full Changelog: [클릭]
누르시면 볼 수 있습니다.

**Comment by kjma8y** [comment]
안그래도 그거 눌러서 보긴 했는데 11111써있고 내용 별로 없길래 다른게 더 있겠지 싶었음...

**Comment by green1052** [comment]
![Screenshot_20230209_035909_Bromite](https://user-images.githubusercontent.com/34261355/217626236-7077a55b-5efe-4c0d-bf75-19979d296eaf.png)

![Screenshot_20230209_035903_Bromite](https://user-images.githubusercontent.com/34261355/217626267-d388388b-7125-4459-b61d-2fbbc48735db.png)

1로 된 부분은 귀찮아서 생락한거고
조금 위로 올리면 수정된 부분 적혀있읍니다

**Comment by green1052** [comment]
수정됐습니다.
