### ISSUE TITLE
목록 갱신시 현재 글이 공지 최상단으로 올라감

### ISSUE THREAD

**Issue by sanekata** [green1052/DCRefresher-Reborn#203]
**버그 설명**
![image](https://github.com/user-attachments/assets/74fbc8ad-4f2f-463a-b2ad-962a9e85a0d2)
글 읽기 화면 아래 글 목록 갱신시 이런식으로 현재 읽고 있는 글이 공지 최상단으로 잘못 올라갑니다
+ 일부 공지도 중복해서 표시됩니다.

**재현 방법**
갤러리 아무 글이나 읽는 중 하단 글 목록 보기

**예상 동작**
정상적으로 글 목록이 갱신됨

**스크린샷**
![image](https://github.com/user-attachments/assets/74fbc8ad-4f2f-463a-b2ad-962a9e85a0d2)

**환경:**
 - OS: Windows 11
 - 브라우저: Chrome
 - 버전: 130

**추가 설명**
갤러리 목록 화면에서는 아무 이상 없습니다.

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/commit/75895036c6b93ba05f612409c6242f4b99d8c969
