### ISSUE TITLE
게시글에서 글쓴이 -> 차단닉네임으로 잘못 차단했는데 어떻게 풀어야하나요??

### ISSUE THREAD

**Issue by Hakjin97** [green1052/DCRefresher-Reborn#205]
**기능 요청 이유**
차단 해제하는 방법을 모르겠습니다

**기능 설명**
설정에 있는 차단 항목에는 차단한 닉네임이 안나옵니다

**추가 설명**

**Comment by green1052** [comment]
차단 목록에 없으면 차단되지 않은 겁니다.
