### ISSUE TITLE
업데이트 이후 폰트교체 풀림 및 글 자동 새로고침 작동안함

### ISSUE THREAD

**Issue by paimon9999** [green1052/DCRefresher-Reborn#21]
폰트교체 기능을 사용하고 있었는데
업데이트 이후 기능이 풀리네요
옵션을 껐다 키면 임시로 적용됐다가 새로고침하면 다시 풀립니다
글 자동 새로고침기능은 작동이 안되네요
Edge 109.0.1518.78 사용하고 있습니다.
조치해주시면 감사하겠습니다

**Comment by green1052** [comment]
수정됐습니다.

**Comment by paimon9999** [comment]
감사합니다 항상 잘 사용하고 있습니다.
