### ISSUE TITLE
메모 관련 문의

### ISSUE THREAD

**Issue by Ryukumtae** [green1052/DCRefresher-Reborn#212]
안녕하세요,
메모한 유저 목록을 열람한다거나...
혹은 메모를 다량 추가(공앱 처럼) 하는 방법은 없을까요?

**Comment by green1052** [comment]
아쉽게도 없습니다.

**Comment by green1052** [comment]
@Ryukumtae 1.9.7 버전 부터 메모 관리 기능을 추가했습니다.

![image](https://user-images.githubusercontent.com/34261355/184473699-de1819b2-20d3-4b24-9dfa-2fa31453c5a2.png)

현재는 등록된 유저 이름 확인과 삭제만 가능하지만 추후에는 수정 기능을 추가할 예정입니다.
