### ISSUE TITLE
게시글에서 답글순으로 자동변경되도록 하실 수 있으신가요?

### ISSUE THREAD

**Issue by fwwe445** [green1052/DCRefresher-Reborn#216]
게시글 볼때마다 댓글을 답글순으로 보고싶은데 디시에선 디폴트가 등록순이라 불편합니다
그냥 페이지 들어가면 자동으로 답글순으로 댓을 볼 수 있게 하는 기능 가능하시면 부탁드립니다

**Comment by green1052** [comment]
해당 기능을 추가할 필요를 느끼지 못해 따로 유저 스크립트를 사용하시는 법을 추천 드립니다.

해당 코드를 바이올렛 몽키 같은 유저스크립트 확장을 통해 등록하셔서 사용하시면 됩니다.

추가로 해당 스크립트를 사용하시면 자동으로 답글 순으로 변경되어도 
설정은 등록순으로 표기됩니다.

![image](https://user-images.githubusercontent.com/34261355/181337226-b8460e5b-2c49-41b4-9e0a-663b8c69f972.png)


```js
// ==UserScript==
// @name 몰루
// @version 1.0.0
// @author green1052
// @description 디시 댓글 설정 자동으로 설정
// @match http*://gall.dcinside.com/*
// @namespace dcdc
// @rut-at document-end
// @noframes
// ==/UserScript==

(() => {
"use strict";

// D = 등록순
// N = 최신순
// R = 답글 순
if(viewComments !== undefined) viewComments(1,"R");
})();
```

**Comment by fwwe445** [comment]
오우 이제봐서 죄송합니다
그리고 코드 짜주셔서 감사합니다
유용하게 잘쓰겠습니다
