### ISSUE TITLE
파이어폭스 설치 방법 오류

### ISSUE THREAD

**Issue by distortedspacetime** [green1052/DCRefresher-Reborn#218]
3. xpinstall.signatures.required 값 true로 변경
이 항목이 마지막으로 가야하지 않을까요?

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/188315938-008130f2-a7ff-42b6-ab07-7ae9f56681aa.png)

https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by green1052** [comment]
xpinstall.signatures.required 값을 먼저 false로 설정 해야 인증되지 않은 확장프로그램을 설치할 수 있습니다.
