### ISSUE TITLE
v3.9.0 업데이트 이후 스텔스 모드 작동 오류

### ISSUE THREAD

**Issue by Lucid0418** [green1052/DCRefresher-Reborn#22]
v3.9.0 업데이트 이후부터 스텔스 모드가 작동하지 않습니다
모듈에서는 모드가 활성화 되어 있는데 실제 게시물에서는 바로 짤이 보이고 옆 플로팅 버튼과 일시 비활성화 단축키도 먹히지 않네요.

크롬 110.0.5481.78 사용중입니다.

번거로우시겠지만 확인 부탁드립니다.

**Comment by green1052** [comment]
수정됐습니다.
