### ISSUE TITLE
2.0.0 업데이트 이후 설정창 오류

### ISSUE THREAD

**Issue by Lucid0418** [green1052/DCRefresher-Reborn#222]
![image](https://user-images.githubusercontent.com/18731129/193163907-405aa566-fb7c-425d-a96b-1077a3ff9ba3.png)

설정을 바꾸려고 하면 위와 같이 나오고 다른 설정탭으로 이동도 되지 않습니다.
자동 새로고침 자체는 작동하고 있는 것 같네요.

삭제 후 재설치를 해봐도 증상이 여전합니다.

**Comment by green1052** [comment]
혹시 브라우저 어떤거 사용하시나요?

**Comment by green1052** [comment]
크롬에서 오류 나네요 수정후 알려드리겠습니다.

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/releases/tag/2.0.1

2.0.1 버전에서 해결됐습니다.
