### ISSUE TITLE
컴팩트 모드 오른쪽 여백 관련

### ISSUE THREAD

**Issue by tokataka** [green1052/DCRefresher-Reborn#223]
![image](https://user-images.githubusercontent.com/22884343/194547973-24ef837b-8d4a-4217-87af-f0d3e89b3d22.png)

```
<div class="ad_bottom_list" style="clear:none;float:left;width:840px">
	<ins class="kakao_ad_area" style="display:none;" data-ad-unit="DAN-urrwd9deagdd" data-ad-width="728" data-ad-height="90"></ins> 
<script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async=""></script></div>
```

컴팩트 모드 강제적용시 위와 같이 .ad_bottom_list에 `width: 840px`가 하드코딩되어있어서 그만큼 여백이 생기는 것으로 보이는데 확인 부탁드립니다

**Comment by green1052** [comment]
제가 컴팩트 모드를 자주 사용하지 않아
문제 없던 모습을 모르겠는데

대락 어떤 모습이였나요?

**Comment by tokataka** [comment]
![image](https://user-images.githubusercontent.com/22884343/194685587-c5e7d1ae-da8e-4b49-9099-7f6789c2b183.png)

이런식으로 오른쪽 여백이 사라지고 좌우폭이 max-width에 맞춰지는게 맞는 형태일것같습니다

위 이미지는 애드블록에 gall.dcinside.com##.ad_bottom_list 필터를 걸었을때입니다

**Comment by green1052** [comment]
테스트 해보니 위에 부분이 짤리는거 같던데
윗 부분이 짤려있나요?

**Comment by tokataka** [comment]
로그인 버튼 있는쪽이 상단이랑 살짝 겹치는것처럼 보이기는 했어요

**Comment by green1052** [comment]
수정하고 알려드리겠습니다

**Comment by green1052** [comment]
2.0.2 릴리즈에서 수정됐습니다.
