### ISSUE TITLE
차단기능 불일치 불포함 오류

### ISSUE THREAD

**Issue by sweeeeeeeety** [green1052/DCRefresher-Reborn#23]
해당 목록에 하나만 등록이 되있는 경우 정상적으로 작동하나
두개이상 등록된경우 or로 작동하여 오류가 나는것같습니다

예시
123.123 불일치 차단하고 100.100 불일치 차단할경우 두 아이피만 보여야하지만 둘다 차단되어 안보임

**Comment by green1052** [comment]
차단 확인 로직이 해당 기능을 지원하지 않아 그렇습니다.
정규식으로
```(123\.123)|(100\.100)```
이런식으로 작성하시면 될겁니다

**Comment by sweeeeeeeety** [comment]
감사합니다
