### ISSUE TITLE
존경하고 사랑하는 개발자님

### ISSUE THREAD

**Issue by ELG66** [green1052/DCRefresher-Reborn#24]
아뢰옵기 송구하오나
업데이트 후
미리보기 창에 다크모드가 적용이 제대로 되지 않는 경우가 발생하옵니다
다크모드를 껐다가 다시 켜면 그 갤러리에서는 적용되지만 창을 닫고 다시 열거나, 다른 갤러리로 이동시 다시 다크모드가 풀리나이다

부디 하해와 같은 마음으로 제 넋두리를 용서하소서

**Comment by green1052** [comment]
리프레셔 버전이 어떻게 되시나요

**Comment by green1052** [comment]
3.9.1 버전에서 수정된 이슈인거 같아 닫겠습니다.
