### ISSUE TITLE
업데이트 후 글 자동 새로고침 기능 작동 안 함

### ISSUE THREAD

**Issue by paimon9999** [green1052/DCRefresher-Reborn#25]
3.9.1 업데이트 후 글 자동 새로고침 기능이 작동하지 않습니다.
옵션은 전부 기본 옵션입니다.
크롬 110.0.5481.78, 엣지 109.0.1518.78 사용중입니다.
수정해주시면 감사하겠습니다.

**Comment by green1052** [comment]
related #16
