### ISSUE TITLE
미리보기로 댓글/답글 작성 후 처리하는 동안 다른 글에 가면 다른 글에 댓글이 달립니다

### ISSUE THREAD

**Issue by Gnbrkm41** [green1052/DCRefresher-Reborn#26]
디시의 문제인지 확장프로그램의 문제인지는 모르겠습니다. 자주 그러는 건 아니고 한두번씩 댓글 달아도 안달리길래 뭔가 하면 위아래글에 달려있음...

**Comment by green1052** [comment]
스크롤 위로 올리거나 내리셔서 게시글 이동하시고 난뒤 그러나요?

**Comment by green1052** [comment]
아니면 뒤로가기로 미리보기 창을 열고
댓글을 쓸때 그러시나요?

**Comment by Gnbrkm41** [comment]
스크롤 기능은 사용하지 않습니다만 가끔 실수로 위아래로 내리다 넘어가는 경우는 있고 뒤로가기는 꽤 사용하는 편입니다

**Comment by green1052** [comment]
시간 날때 테스트해보겠습니다.

**Comment by Gnbrkm41** [comment]
추정: 댓글 엔터치고나면 가끔 서버문제인지 로컬 코드문제인지 한참동안 반응 없을 떄 있는데 그 반응 없는 동안 미리보기 닫고 딴 페이지 미리보기 열면 앞 페이지에서 연 댓글이 뒷 페이지에 달리는 것 같음. 댓글에 답글 다니까 안달리길래 딴페이지 갔다왔는데 한참 지나서 보니까 딴페이지 첫 댓글에 원댓글 없는 답글만 덜렁 달려있었음. 바로 위/아래 글도 아니고 한참 떨어진 글이라 이쪽이 더 가능성 높아보이는 듯?
