### ISSUE TITLE
디시 페이지에서 설정 열어도 "디시인사이드 페이지를 열고 설정해주세요" 표시됨

### ISSUE THREAD

**Issue by Gnbrkm41** [green1052/DCRefresher-Reborn#28]
![image](https://user-images.githubusercontent.com/42944058/218108251-77822b23-5dfa-45d1-ad76-19c61afe714c.png)
![image](https://user-images.githubusercontent.com/42944058/218108299-fa5579f2-722c-4ffd-8334-fb067ffc5a1f.png)

정확한 원인은 불명이나 페이지 열어두고 방치하면 발생하는건지 뭔지 갤질하다보면 발생합니다. 연관 있을진 모르겠지만 글목록 자동갱신이랑 미리보기 켜뒀습니다. 발생 시 페이지 새로고침하기 전까지 설정 페이지 사용 불가능합니다.

팝업 페이지 로그 첨부합니다...만 저 에러 3개는 정상 작동할 때도 떠있는 듯 함.

**Comment by Gnbrkm41** [comment]
추정: 간혹 (디시 페이지) 콘솔에 예외 발생하는데 예외 발생할 시 그러는 걸지도?
![image](https://user-images.githubusercontent.com/42944058/218110440-201adf68-3f18-4e30-b652-392a88065e54.png)

![image](https://user-images.githubusercontent.com/42944058/218110575-67dded4a-abe8-4c5a-81ca-5f86581b1b4b.png)

정확히 어떤 경우 예외 발생하는지는 불명입니다. 목록 새로고침하다 발생하거나 미리보기 열었다 닫았다 하다 발생하는 거로 추정...

**Comment by green1052** [comment]
https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/
