### ISSUE TITLE
특정문자열 아이디를 가진사람 자동차단/자동삭제

### ISSUE THREAD

**Issue by plainwaffle22** [green1052/DCRefresher-Reborn#31]
매크로 프로그램을 사용하여 갤러리를 돌아다니며 구걸을 하거나 바이럴을 하는 아이디가 있습니다. 꾸준히 삭제/차단해본 결과

ooss800
ooss1111
ooss7000
ooss10000 
등등..
닉네임은 다르지만 아이디에서 공통점을 발견할 수 있습니다.
10만원만 빌려줘..15만원으로 갚을게..우리 삼촌좀 도와줘..
이른시간부터 죄송합니다..눈물만 흐릅니다..
교촌,굽네 총5마리 다 합쳐서 6만원에팜
과 같이 갤러리 성향과는 다른 이상한 글을 쏟아내고 있습니다.

혹시 이런 아이디와 같은 경우에 자동 차단(이게 제일 좋음, 30일 차단, 사유는 아무거나(광고/도배면 좋을것같습니다)) 혹은 자동삭제를 할 수 있게끔 만들어주실 수 있을까요?

**Comment by green1052** [comment]
해당 기능은 DCRefresher-Reborn의 개발 목적에 부합하지 않는거 같아 
반려하도록 하겠습니다.

또 개발한다 하더라도 갤러리에 권한을 가지고 있는 계정이 없기 때문에 어려울 듯 합니다.

값싼 파딱을 쓰시는걸 추천드립니다.
