### ISSUE TITLE
게시글 미리보기 시도하면 레이아웃이 왔다갔다합니다.

### ISSUE THREAD

**Issue by Sisimiut** [green1052/DCRefresher-Reborn#32]
평소에 게시글 미리보기 옵션에 키 반전을 적용하여 요긴하게 사용 중인데...

자꾸 열람 중일때랑 아닐때랑 레이아웃이 왔다갔다해요...

**Comment by green1052** [comment]
동영상이나 상세한 설명을 해주세요

**Comment by Sisimiut** [comment]
![bug](https://user-images.githubusercontent.com/125760327/219882319-feda37ce-cb5a-4c42-84b3-f1ea3d6cf181.gif)


녹화된 화면과 같이 레이아웃이 옆으로 왔다가 다시 돌아갔다 합니다.
일부러 평소에 사용한 적이 없는 엣지 브라우저로 테스트했습니다.

**Comment by green1052** [comment]
해당 문제를 재현 할 수 없습니다.

**Comment by green1052** [comment]
수정했습니다.
