### ISSUE TITLE
댓글에 달린 댓글(대댓글)에 차단 대상 포함 시 일괄 차단되는 현상

### ISSUE THREAD

**Issue by jadeclub3** [green1052/DCRefresher-Reborn#33]
안녕하세요

현재 차단 대상(특정인 혹은 디시콘)이  대댓글을 작성하면 원본 댓글을 포함한 나머지 모든 대댓글이 차단되어 보이지 않게 되던데요,

원본 댓글까지 차단되는 것으로 보아 버그인 것 같긴 한데 혹시 개발자님이 의도하신 기능인지 애매하여 문의 드립니다.

혹여나 의도된 사항이라면 차단대상의 대댓글만 차단하고 나머지 원본댓글과 대댓글은 표시되도록 하는 게 더 좋은 것 같습니다. 고맙습니다.

**Comment by green1052** [comment]
#34 해당 작업 마무리 후 수정하겠습니다.
