### ISSUE TITLE
잡다제거 + 컴팩트모드 사용중 클릭안되는 영역

### ISSUE THREAD

**Issue by sysilion** [green1052/DCRefresher-Reborn#37]
<img width="1425" alt="스크린샷 2023-03-17 오후 1 50 01" src="https://user-images.githubusercontent.com/2581852/225816274-e82abe33-be2e-4c26-9809-597a79e5562f.png">

저 영역 클릭이 안됩니다

**Comment by green1052** [comment]
재현 불가능합니다.

**Comment by sysilion** [comment]
그냥 광고제거 확장으로 stickyunit 제거했습니다.
