### ISSUE TITLE
혹시 우클릭으로 게시글 열었을때 댓글 달 수 있을까요

### ISSUE THREAD

**Issue by plainwaffle22** [green1052/DCRefresher-Reborn#4]
일반 텍스트뿐만 아니라 디씨콘도 쓸수 있으면 더욱 좋지만 그게 안된다면 텍스트만으로도 감사합니다

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/204083802-1bc65dfb-1c9c-4be0-9507-ed4f3185c19d.png)

**Comment by green1052** [comment]
텍스트만 작성 가능하지만 있습니다.

**Comment by plainwaffle22** [comment]
감사합니다 :D
