### ISSUE TITLE
리프레셔 사용 시 알림 리스트 버튼이 동작하지 않습니다.

### ISSUE THREAD

**Issue by scarf005** [green1052/DCRefresher-Reborn#43]
![233820126-90765fcf-55dc-4330-9be7-f4534b64a941](https://user-images.githubusercontent.com/54838975/233828690-477530fc-8e3f-44c8-900e-1232edb8e78c.png)
리프레셔를 사용중이라면 여기서 알림 리스트를 클릭하여도 알림 목록이 뜨지 않습니다.

![image](https://user-images.githubusercontent.com/54838975/233820104-641cfc3e-1c2d-4865-918b-e5c8f8632686.png)
알림 목록의 모습입니다. 기존 알림 리스트 기능을 복구하거나, 새로운 알림 UI가 생긴다면 좋을 것 같습니다.

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/233842069-cdb3ed32-e255-45ee-a734-f398d148d84b.png)

이 부분 말씀하시는건가요?

**Comment by scarf005** [comment]
현재 `컴팩트 모드 강제 사용` 및 `잡다 링크 숨기기` 을 사용중이어서 보여주신 알림 아이콘은 보이지 않고 있습니다.
말씀드린 알림 리스트는 페이지 최상단의 갤로그 등이 있는 네비바의 아이디를 클릭시 나오는, `운영/가입` 밑 알림 리스트입니다.

**Comment by green1052** [comment]
디시 아이디가 없어서 테스트하기 어렵네요

**Comment by green1052** [comment]
`컴팩트 모드 강제 사용`, `잡다 링크 숨기기` 꺼도 그러시나요?

**Comment by scarf005** [comment]
둘다 끄면 잘 동작합니다

**Comment by green1052** [comment]
`컴팩트 모드 강제 사용`만 활성화 하셨을때는요?

**Comment by green1052** [comment]
아 발견했습니다.

**Comment by green1052** [comment]
[dist.zip](https://github.com/green1052/DCRefresher-Reborn/files/11303873/dist.zip)

해당 버전 확인 부탁드립니다.

**Comment by green1052** [comment]
[설치법](https://sunstar2.tistory.com/1676)

**Comment by green1052** [comment]
알람 보이시나요?

**Comment by scarf005** [comment]
사실 로컬에서 빌드해서 테스트해보려고 했는데 잘 안되네요
```
pnpm add glob-parent
Already up to date
Progress: resolved 536, reused 527, downloaded 0, added 0, done
Done in 3.3s

pnpm build:mv3

> dcrefresher-reborn@3.9.7 build:mv3 /home/scarf/repo/etc/DCRefresher-Reborn
> webpack --env manifest=manifest_v3.json --config webpack.prod.js

[webpack-cli] HookWebpackError: Your application tried to access glob-parent, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

**Comment by green1052** [comment]
위에 빌드한 파일 올려드렸어요

**Comment by scarf005** [comment]
파이어폭스에서 설치가 안되어서 크롬으로 다시 설치했습니다. 이제 잘 동작하나, 화면 크기가 전체화면이 아닐 시에는 알림 리스트 버튼이 화면에서 보이지 않는 문제가 있습니다.
![로그라이크 갤러리 - 커뮤니티 포털 디시인사이드 - Chrome_01](https://user-images.githubusercontent.com/54838975/233844754-f720ef2f-72b8-4266-bfaf-4fe1320ffea9.png)
(전체화면 모드)
![로그라이크 갤러리 - 커뮤니티 포털 디시인사이드 - Chrome_02](https://user-images.githubusercontent.com/54838975/233844757-7cf4776b-ad3b-4cd1-9f80-f25dc55097de.png)
(Meta + 왼쪽 방향키로 가로 크기를 50%로 축소)

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/233845190-2bff7599-fa49-438b-8cfe-a715e342f292.png)

최상단에 있는 알람 버튼 요소 사진 좀 보내주실 수 있나요?
위에 사진 처럼요

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/233875815-c748042e-c506-468c-9b92-fd1a71ce1811.png)

### 해당 html 태그
```html
<a href="javascript:;" onclick="alarmList($('.icon_noti', this), 'new','H')">알림 리스트</a>
```

### css 선택자
```ts
document.querySelector('#user_data_lyr .user_data_list li:nth-child(5) a')
```

<details><summary>전체 컨텍스트</summary>

```html
<div id="user_data_lyr" class="user_data" style="right: 0px; top: 25px;">
  <ul class="user_data_list">
    <li>
      <a href="https://gallog.dcinside.com/pig005">MY갤로그<em class="sp_img icon_go"></em></a>
    </li>
    <li>
      <a href="https://sign.dcinside.com/myinfo/modify">고정닉정보<em class="sp_img icon_go"></em></a>
    </li>
    <li>
      <a href="javascript:;" onclick="myFavorite('50%')">즐겨찾기</a>
    </li>
    <li>
      <a href="javascript:;" id="my_minor_btn_h" onclick="toggle_my_minor_pop(this)">운영/가입</a>
    </li>
    <li>
      <a href="javascript:;" onclick="alarmList($('.icon_noti', this), 'new','H')">알림 리스트</a>
    </li>
  </ul>
</div>
```

</details>

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/233938171-5a88e81b-6ecb-43be-a8fe-eef26055dc0d.png)

**Comment by green1052** [comment]
해당 문제를 재현 할 수 없습니다.

**Comment by green1052** [comment]
```js 
alarmList($('.icon_noti', this), 'new')
```
![image](https://user-images.githubusercontent.com/34261355/233938631-34b9e819-9b6b-4fbd-a665-e22ddde4a887.png)


```js
alarmList($('.icon_noti', this), 'new','H')
```

![image](https://user-images.githubusercontent.com/34261355/233938665-ece0fbd7-2d14-4653-9365-642e3a9c9c20.png)

**Comment by scarf005** [comment]
https://user-images.githubusercontent.com/54838975/233941689-8f2b611d-0534-4831-8ee7-b7c4f949aa43.mp4

chrome에서 [해당 수정본](https://github.com/green1052/DCRefresher-Reborn/issues/43#issuecomment-1519071471)을 적용한 상태입니다. 화면 크기가 일정 크기 이하로 줄어들면 알림 리스트가 보이지 않습니다.

`컴팩트 모드 강제 사용`, `갤러리 뷰 숨기기`, `잡다 링크 숨기기` 적용 상태입니다.

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/235281635-d53acc2b-a191-49ad-8b84-26cef3d2d373.png)

![image](https://user-images.githubusercontent.com/34261355/235281638-2b8fc0d6-d551-4996-84ca-cab26e1482be.png)

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/235281710-6b024c44-ca41-4c12-8e19-b30b7eb100b1.png)

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/235281714-21befce1-1b0f-43a9-b840-a252fe3c5f9c.png)
