### ISSUE TITLE
Can't Find File Err

### ISSUE THREAD

**Issue by Sayori1576** [green1052/DCRefresher-Reborn#48]
![제목 없음](https://user-images.githubusercontent.com/93511899/156987015-a9bdbd9c-6598-482a-a818-fb5a4a520286.png)
No Icon and No page.

**Comment by green1052** [comment]
🤔 github action error

https://github.com/green1052/DCRefresher-Reborn/releases/tag/1.2.0

if you cant wait download 1.2.0

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/releases/tag/1.4.1 fixed
