### ISSUE TITLE
3.9.15로 업데이트되면서 오른쪽 클릭으로 차단 메모하던 기능이 사라짐

### ISSUE THREAD

**Issue by shyluy** [green1052/DCRefresher-Reborn#54]
3.9.15로 업데이트되면서 오른쪽 클릭으로 차단 메모하던 기능이 사라짐 일일히 입력해서 차단해야함 파이어폭스 크롬 전부 안 되는거 확인

**Comment by shyluy** [comment]
추가로 재설치시에는 작동이 잘 되다가 껐다 켜면 우클릭 리프레셔 도구가 안 보임 (파이어폭스)

**Comment by green1052** [comment]
재현 불가능힙니다.
![image](https://github.com/green1052/DCRefresher-Reborn/assets/34261355/b00bc83e-1155-4f24-ae5d-b4c6b5191192)

**Comment by Morgenta** [comment]
저도 파이어폭스 사용자인데 업데이트 이후로 안되네요

다른확장기능이랑 충돌인가 싶어 다른 확장기능 전부 제거 후 리프레셔만 설치를 했을 때도 뜨지않고
파이어폭스 첫 설치 및 리프레셔 첫 설치에만 우클릭 도구가 보입니다

윈10 pro 64비트 입니다
