### ISSUE TITLE
preview에서 한글로 댓글을 쓸때 커서위치에 따라 한글자씩 잘리는 현상

### ISSUE THREAD

**Issue by wonkyDD** [green1052/DCRefresher-Reborn#57]
커서가 이렇게 마지막글자의 종성에 있을때 댓글 작성시 다음과 같이 보여지게 됩니다.

<img width="713" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/30d1fabc-582a-4383-941a-347ebd521bab">

<img width="294" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/eaad517c-3b61-4d2c-b163-f28f51c54364">

<br/>
<br/>

하지만 커서가 종성이 아닌 문장 끝에 위치할 경우

<img width="495" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/3c09c7b2-56e6-4603-a1ca-7422abf98120">

<img width="269" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/0c30899c-b44f-41d2-8763-af48ea45dcd6">

제대로 출력이 됩니다.

<br/>
<br/>

---

[문제라고 생각되는 부분](https://github.com/green1052/DCRefresher-Reborn/blob/main/src/components/write_comment.vue#L222)

code상에서 `this.text`를 제거하고
func의 두번째 파라미터 자리에 대신 `this.getDccon( ) ?? textarea.value` 로 대체했더니 잘 작동했습니다.
하지만 너무 workaround같은 느낌이라 pr대신 일단 이슈로 남겨봅니다.

항상 감사히 잘 쓰고 있습니다.
포크이후로 유지해주셔서 감사합니다.

**Comment by green1052** [comment]
재현 불가능합니다.
운영체제와 사용하시는 브라우저를 알려주세요

**Comment by wonkyDD** [comment]
@green1052  앗 죄송합니다.
macOS ventura와 edge브라우저 입니다.

**Comment by green1052** [comment]
`https://github.com/vuejs/vue/issues/10424`
찾아보니 macOS에서만 발생하는 문제네요
시간날때 수정하겠습니다.
