### ISSUE TITLE
오른쪽 클릭 메뉴에 dc reborn메뉴가 나오지 않음

### ISSUE THREAD

**Issue by guljam** [green1052/DCRefresher-Reborn#58]
파이어폭스 쓰고있습니다

가끔 유저 차단해야할 일이 생기는데
예전에는 오른쪽클릭 메뉴에 차단 메뉴가 잘 나오다가 이제는 안나와요

이것때문에 어제 애드온을 제거하고 다시 깔아봤는데 
정상 작동하다가 다시 없어졌습니다

현재 사용하고있는 오른쪽 메뉴를 사용하는 애드온은

ublock origin
TWP구글번역기
search by image 3개입니다
유독 dc애드온만 작동하지 않네요

다른 버그들같은 경우

자동 새로고침 기능이 작동하지 않고
게시글을 오른쪽 클릭해서 게시글을 볼 경우 기능이 작동하지 않고
이 상태에서 추천을 누를경우 오류메시지가 뜹니다

애드온끼리 충돌 가능성이 있는것 인가요?

**Comment by green1052** [comment]
#54
