### ISSUE TITLE
개선사항 몇가지 요청

### ISSUE THREAD

**Issue by MongsilDev** [green1052/DCRefresher-Reborn#6]
1. 모듈 -> 다크 모드 활성화시 게시글 목록에서 이미 조회한 게시글과 아닌글을 색상으로 구별할 수 없어서 불편함
2. 2560x1440 32" 모니터 사용중, 보통 오른쪽 화면 절반 (윈 + 오른쪽 방향키)에 브라우저 켜놓고 갤질하는데 오른쪽으로 치우쳐진걸 클린디씨 노멀형처럼 옮겨줬으면 좋겠음 (사진 첨부, 딱 사진 사이즈로 보임)
이게 DCRefresher
![1](https://user-images.githubusercontent.com/94197378/204143684-5a5f6f04-2616-4e0e-bb3d-2a8c40eda134.png)
이건 클린디씨 노멀형, 지금보니 좌우로 스크롤할 여백이 없네
![2](https://user-images.githubusercontent.com/94197378/204144713-790023c6-94ae-4a65-a1ae-511b90b33837.png)
3. 아이피 뒤에 `ㅇㅇ(220.71) KT ` 이렇게 보이는걸 DIBE처럼 `ㅇㅇ(220.71) [KT]` 이렇게 메모에 괄호처리하고 색상도 바꾸는게 보기편할거같음 
4. `툴팁 미리보기 표시` 활성화시 게시글 위에 뜨는 팝업 width 절반정도로 줄이면 좋겠음, 그리고 팝업에 뜨는 이미지 사이즈를 가능하다면 강제로 줄이고 보이는 텍스트 양을 늘리면 좋겠음 
5. 블러항목에 적혀있는 `(일부 성능 영향 있음)` 이 성능 상승인지 하락인지 표시해주면 좋을거같음 
6. `툴팁 미리보기 표시` 가 활성화 되는 영역이 게시글이 있는 라인 전체가 아니라 게시글 제목 텍스트가 있는 부분에만 활성화됐으면 좋겠음 `td.gall_tit.ub-word` -> `td.gall_tit.ub-word.a` 맞나? 

확장프로그램 오랫만에 좋은거 찾아서 잘 쓰고있습니다 감사합니다.

**Comment by green1052** [comment]
1. 
![image](https://user-images.githubusercontent.com/34261355/204340334-da759823-c83f-4803-a09b-7026914b5a1c.png)
이렇게 회색으로 표시되어 가시성이 떨어진다는 건가요? 아니면 색이 안 바뀐다는 건가요?

**Comment by green1052** [comment]
2.
margin: 0 auto라 항상 중앙에 있을겁니다..
쉬프트 스크롤로 땡겨서 사용하시는걸 추천드립니다..

![image](https://user-images.githubusercontent.com/34261355/204342743-2ef480c1-dfbd-46de-8c6b-7abe34c3461d.png)

이렇게요

**Comment by MongsilDev** [comment]
1. 네이버 웨일의 `웹 콘텐츠 다크모드 사용` 체크시 게시글을 조회해도 회색으로 보이지않고 동일하게 흰색으로 보이네요, 확인을 했어야했는데 생각을못했습니다.

**Comment by green1052** [comment]
3. 괄호 처리 하는 게 더 좋아 보이네요. 색상도 추가해보겠습니다.

**Comment by MongsilDev** [comment]
![image](https://user-images.githubusercontent.com/94197378/204343519-fe04a6cf-5267-43ac-819a-409bd7ff3068.png)
게시글 상세보기에서 유동닉네임 클릭 시 사진처럼 `작성글 검색` 버튼이 2중으로 표시가 되는데 한번 확인해보시면 좋을거같습니다.

**Comment by green1052** [comment]
4.  설정으로 툴팁 사이즈를 조절하게 해보겠습니다,
이미지 사이즈 조절은 전에 비슷한 이슈가 있었으나 #2 이미지 숨기는 설정으로 대체했습니다.

5. 수정하겠습니다.

6. 혹시 게시글 목록 인식 범위 확장 설정을 따라가게 수정하겠습니다.

**Comment by green1052** [comment]
> 

![image](https://user-images.githubusercontent.com/34261355/204344120-ec5b2e75-3c72-4c0d-a698-74ee920fdf64.png)

따로 리프레셔나 브라우저에서 설정하신게 있으신가요?

**Comment by MongsilDev** [comment]
게시글 목록말고 게시글 클릭후에 나오는 창에서 한번 확인해보실래요?
시크릿모드에서 `DCRefresher`에만 권한을 부여후에 확인해봐도 동일하네요.

![image](https://user-images.githubusercontent.com/94197378/204344611-1a20056b-17e7-4add-8a2e-a2ace46bd14f.png)

**Comment by green1052** [comment]
그러네요 중첩되서 표시되네요 이것도 한번 확인해보겠습니다.

**Comment by green1052** [comment]
- [x] IP 정보 표기 방식 개선
- [x] 블러 항목 문구 수정
- [X] 유동 작성글 검색 중첩 문제 수정

**Comment by green1052** [comment]
6번 항목은 확인해보니 `게시글 목록 인식 범위 확장` 설정을 따라가네요

**Comment by green1052** [comment]
[3.6.2](https://github.com/green1052/DCRefresher-Reborn/releases/tag/3.6.2)에서 반영됐습니다.
