### ISSUE TITLE
우클릭 미리보기가 동작하지 않습니다

### ISSUE THREAD

**Issue by wonkyDD** [green1052/DCRefresher-Reborn#62]
OS: macos sonoma
browser: Version 119.0.6045.199 (Official Build) (arm64)

https://github.com/green1052/DCRefresher-Reborn/commit/2252bd44d54e3fd786fa16543e2b724ab4fd0b35
위 커밋해시까지 로컬에서 빌드해서 사용중인데 우클릭 미리보기가 되지않고있습니다.

**Comment by green1052** [comment]
오류 로그 좀 보여주세요

**Comment by wonkyDD** [comment]
> 오류 로그 좀 보여주세요

깜빡했습니다 죄송합니다.

<img width="621" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/41f70671-2897-419b-a68d-2b5c00f9394e">


우클릭 하는 순간 위 에러가 에러탭에서 추가됩니다.

**Comment by wonkyDD** [comment]
3.10 릴리즈 cd57a12dbca8e216c15edc62efb6c8384790a508 로 다시 돌려서 빌드했을때는 문제없음을 확인했습니다.

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/commit/4356c56942a52d4b5d17b1a4c62094b9444ce438

툴탭 관련 같은데
혹시 한번 끄고 해보시겠어요?

**Comment by wonkyDD** [comment]
@green1052  답변늦어서 죄송합니다.

툴탭이라고 하면 팝업에서 일반 > 미리보기 > 툴팁을 잘못말씀하신건가요?
아니면 툴탭이라고 하는 것이 따로 있는건가요..?

**Comment by green1052** [comment]
툴팁입니다.

**Comment by wonkyDD** [comment]
@green1052  확인했습니다.

<img width="623" alt="image" src="https://github.com/green1052/DCRefresher-Reborn/assets/81248624/306f185a-4e38-496a-8c6d-0d0abc4a95d3">

말씀하신대로 `툴팁 미리보기 표시`를 on하지 않은 상태에서는
우클릭 했을때 preview가 되지 않네요.

미리보기 on 하지 않고서 우클릭만해도 preview가 가능하던 이전의 동작은 더이상 지원되지않는 건가요?

https://github.com/green1052/DCRefresher-Reborn/commit/02cdf25f12a11cdebc6e0ccfe7318ddcf6d609e1
이번에 새롭게 작업하신 develop 브랜치를 따서 확인해보니까
여기서는 on하지 않아도 우클릭했을때 preview가 되길래 한번 여쭈어봅니다 ! 👀

**Comment by green1052** [comment]
아니요, 툴팁 기능을 비활성화해도 미리보기 기능은 작동합니다.

**Comment by wonkyDD** [comment]
@green1052 감사합니다. 그냥 사용자 문제였네요. 🙇
