### ISSUE TITLE
IP 표시 건의 및 미리보기에서 댓글 질문사항

### ISSUE THREAD

**Issue by honochika4** [green1052/DCRefresher-Reborn#67]
어쩌다 파폭에 없나 해서 찾아봤는데 좋은 게 있어서 써보는 중입니다

1. 유동 IP 표시하는 건은 여러 나라 인터넷업체? 같은게 여러개 떠서 난잡한데 혹시 한국 통신사나 인터넷업체만 표시하는 방식이 어떠한가 싶네요
ip 데이터베이스를 잘 모르겠지만 안된다면 하다못해 한국 업체를 제일 앞으로 해주시면 감사하겠습니다.

2. 우클릭 미리보기 창에서 댓글을 쓰려고 하니 
"알 수 없는 경로로 접근하였습니다. 다시 시도해주세요[ERROR-C1]"
이라고 뜨네요
해결이 될 수 있었으면 좋겠습니다

그리고 혹시 자짤기능은 이슈를 보니 만들었던거같은데 지금은 막혀있는데 막아두신건가요?

수고하세요

**Comment by green1052** [comment]
1. 수정하겠습니다.

2. https://github.com/green1052/DCRefresher-Reborn/discussions/41
파이어폭스에서만 발생하는 오류입니다, 해당 내용대로 설정해보세요

3. #8 아직은 자짤 기능 설정만 있고 기능 구현은 하지 않은 상태입니다.

**Comment by honochika4** [comment]
감사합니다. 근데 2번은 사생활 모드는 아닌데 저 에러가 뜨네요... ㅠㅠ

**Comment by green1052** [comment]
2번 수정됐습니다.

참고 자료: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#xhr_and_fetch
