### ISSUE TITLE
스텔스 모드 토글 단축키 추가가 가능할까요?

### ISSUE THREAD

**Issue by Lucid0418** [green1052/DCRefresher-Reborn#7]
![image](https://user-images.githubusercontent.com/18731129/189786118-81c0b0e2-32c8-484e-9eb3-558e1a90d708.png)
![image](https://user-images.githubusercontent.com/18731129/189786154-a24946ac-037d-4a37-b7b8-4d1a5298d7a9.png)

공앱처럼 본문 내에서 이미지 보기를 빠르게 켰다 껐다 할 수 있으면 좋을 것 같습니다.
현재는 확장 프로그램 전체를 껐다 켜는 단축키를 사용하거나 상단의 확장 프로그램 아이콘을 일일이 클릭해서 기능을 토글하는 방법밖에 없어서 조금 손이 많이 가네요.

번거로우시겠지만 검토 부탁드립니다.

**Comment by green1052** [comment]
켰다 껏다하는게 해당 게시글에서만 임시적으로 비활성화하는걸 말하는건가요?
아니면 완전히 끄는걸 말하나요?

**Comment by Lucid0418** [comment]
단축키 토글이 가능해지면 크게 의미가 없을 것 같긴 하지만
완전히 끄는 편이 좋을 것 같습니다.

**Comment by Lucid0418** [comment]
v3.6.3 오면서 본문에도 이미지 보이기 플로팅 버튼이 생겼네요.
여기에 단축키만 달아주셔도 충분할 것 같습니다.

신경써주셔서 감사합니다.

**Comment by green1052** [comment]
그럼 플로팅 버튼이랑 연동해
누를때마다 보이고 안보이도록 하겠습니다.

**Comment by green1052** [comment]
추가됐습니다.

**Comment by green1052** [comment]
[3.7.0](https://github.com/green1052/DCRefresher-Reborn/releases/tag/3.7.0) 릴리즈에 반영됐습니다.

오래 기다리게 해서 죄송합니다.
