### ISSUE TITLE
모듈 - 다크모드 활성화 후 글 수정시 내용 입력칸 다크모드

### ISSUE THREAD

**Issue by emptycan1010** [green1052/DCRefresher-Reborn#72]
일반적인 글 작성시엔 글 작성창은 하얀색으로 잘 뜨는데
글 작성 후 수정시 글 작성창이 검게 변하여 글을 알아보기 어렵습니다. 수정을 요청드립니다.

**Comment by green1052** [comment]
영상이나 사진 같은 참고자료를 보내주세요

**Comment by emptycan1010** [comment]
![image](https://github.com/green1052/DCRefresher-Reborn/assets/85441644/5636b96c-6284-480d-a7e2-6ca0f971c9c2)
정상적인 글 작성창.
![image](https://github.com/green1052/DCRefresher-Reborn/assets/85441644/659d29a2-f274-4962-9097-8a1cde3b889f)
수정시 글 작성창
