### ISSUE TITLE
글 목록의 갱신이 늦는 문제

### ISSUE THREAD

**Issue by GE-21** [green1052/DCRefresher-Reborn#73]
글에 진입 했을 때 공지 숨김 옵션이 늦게 적용되는 문제
![Honeycam 2024-04-19 21-14-29](https://github.com/green1052/DCRefresher-Reborn/assets/167535395/97706957-3449-42c7-8c5d-f726dda0b8e5)

글에서 뒤로가기를 통해 다시 글목록으로 나왔을 때 최신 글 갱신이 늦는 문제
![Honeycam 2024-04-19 21-16-55](https://github.com/green1052/DCRefresher-Reborn/assets/167535395/5cc8d0f3-1c88-4edc-b461-f83a7b3d5da8)

첫번째 문제는 끄고 사용해도 크게 문제 없다고 생각되는 옵션이여서 평상시에는 끄고 사용중이지만 건의하는김에 같이 올려봅니다.

두번째 문제가 조금 핵심적인 문제인데
전체글 버튼이나, 상단 갤러리명을 통해 다시 글목록으로 바져나가는 경우 문제가 없지만
뒤로가기를 통해 나갈 경우 위의 처럼 새로운 글 갱신이 늦게 되는 문제가 있습니다.

첫 갱신 시도 딜레이를 매우 짧게 만들어주신다거나 다른 방법으로는 해결이 불가능할까요?
![Honeycam 2024-04-19 21-34-20](https://github.com/green1052/DCRefresher-Reborn/assets/167535395/c6df7377-fa14-410d-9f11-d492a99268d4)

**Comment by green1052** [comment]
https://nitropack.io/blog/post/back-forward-cache

**Comment by green1052** [comment]
갱신 지연 문제 다시 수정했습니다.
