### ISSUE TITLE
Sort by like or reply or views count

### ISSUE THREAD

**Issue by Sayori1576** [green1052/DCRefresher-Reborn#74]
Like official app, Please add the function to Display only posts that have received more than a certain number of likes or views or comments

**Comment by green1052** [comment]
in preview mode?

**Comment by Sayori1576** [comment]
![Screenshot_20220410-184605.jpg](https://user-images.githubusercontent.com/93511899/162612502-4c06a45b-3939-495c-9cd6-b5039fb0ea34.jpg)
like this, sort by like count

**Comment by green1052** [comment]
문의 주신 내용을 검토 해보았으나 아쉽게도 구현이 불가능함을 알려드리고 싶습니다.

구현이 가능한지 알아보기 위해 웹사이트를 잠깐 분석했으나
정렬 관련 기능이 있지만 작동하지 않는것으로 사료됩니다.

(list.js의 listSort 함수)

그래서 구현을 위해서는 많은 구현이 필요할 것으로 보여 해당 기능 요청은 아쉽게도 구현이 어렵다고 말씀드리고 싶습니다.

큰 도움이 되지 못하여 죄송합니다.

이슈는 닫겠습니다.

😢
