### ISSUE TITLE
On preview mode, Can't like at post

### ISSUE THREAD

**Issue by Sayori1576** [green1052/DCRefresher-Reborn#75]
Wrong access Err.

**Comment by green1052** [comment]
i can't find error in DCRefresher Reborn 1.6.2, ungoogled chromium 100.0.4896.62

please tell me more information? like browser, cookie settings, etc..

**Comment by Sayori1576** [comment]
![캡처](https://user-images.githubusercontent.com/93511899/162599819-89a42def-2bac-40df-9785-f232772ad321.PNG)
On firefox.

**Comment by green1052** [comment]
please send more info to my email
 
green1052@protonmail.ch

open preview -> open devtool -> move to network tab -> recomment post ->

![image](https://user-images.githubusercontent.com/34261355/162600228-55debcb0-23a7-4fe7-afd8-252ff7540357.png)

right click  ->

![image](https://user-images.githubusercontent.com/34261355/162600283-37bf85b3-9148-4767-bd87-89f18fccd80c.png)

 Save To HAR

**Comment by green1052** [comment]
before must be logout your accout

**Comment by green1052** [comment]
you dont have to send me

i find the problem

**Comment by green1052** [comment]
FireFox 데브툴로 디버깅을 해보았으나
네트워크 탭에서 요청도 안떠서

로그를 찍어가며 해보았으나
문제될 부분이 없습니다.

번거로우시겠지만 고칠 동안에는 개념글 추천은 따로 창을 열어서 추천 해주세요

**Comment by green1052** [comment]
@Sayori1576 are you use firefox private mode?

read this issue
https://github.com/So-chiru/DCRefresher/issues/32
