### ISSUE TITLE
업데이트 후에 미리보기 댓글이 안보여요

### ISSUE THREAD

**Issue by ahpifgpe** [green1052/DCRefresher-Reborn#75]
캬루가 따귀를 맞고 있어요

TYPEERROR: REDUCE OF EMPTY ARRAY WITH NO INITIAL VALUE

**Comment by green1052** [comment]
삭제된 글 보존 기능 키셨나요?

**Comment by ahpifgpe** [comment]
> 삭제된 글 보존 기능 키셨나요?

꺼져있어요
