### ISSUE TITLE
다크 모드 색상 설정

### ISSUE THREAD

**Issue by PangMo5** [green1052/DCRefresher-Reborn#77]
먼저 좋은 확장 만들어주셔서 감사합니다.

다크 모드에서 백그라운드 색상, 텍스트 색상 등을 커스텀 할 수 있게 되면 좋을것 같습니다.

https://github.com/green1052/DCRefresher-Reborn/blob/345857067b8cc3fc479b24eda0a1335c6b789eda/src/styles/darkmode.scss#L1-L17
요 친구들이요.

**Comment by green1052** [comment]
먼저 리프레셔에 관심 가져주셔서 감사합니다,
말씀해주신 기능은 제 실력이 부족해 구현도 어렵고 추가할 필요도 딱히 없다 사료하여

따로 유저스크립트 같은 걸 이용해 css를 삽입하시는걸 권해드립니다.

**Comment by PangMo5** [comment]
아 그렇군여 확인 감사합니다.
