### ISSUE TITLE
글쓸 때 닉네임 관련 건의입니다

### ISSUE THREAD

**Issue by coffeechococake7** [green1052/DCRefresher-Reborn#79]
(+글댓비 관련)
작년 7월 패치 때 *갤러로 고정되게 된거
리프레셔에서 ㅇㅇ 닉으로 고정시키는 기능 만들어주셨으면 합니다
그리고 특정 글에 들어가서 단축키를 누르면 글댓비를 계산해주는 기능도 괜찮을 것 같습니다

**Comment by green1052** [comment]
1. ㅇㅇ 고정 기능은 딱히 추가할 이유가 없어 보입니다.
2. 글댓비 기능은 개선 예정입니다.
