### ISSUE TITLE
자동짤방 기능 추가

### ISSUE THREAD

**Issue by woofingcough** [green1052/DCRefresher-Reborn#8]
번거로우시겠지만 혹시 괜찮으시다면 자동짤방 첨부 기능을 추가해주실 수 있는지 궁금합니다.

**Comment by Gnbrkm41** [comment]
FWIW [디시 자동짤방 - Chrome Web Store](https://chrome.google.com/webstore/detail/%EB%94%94%EC%94%A8-%EC%9E%90%EB%8F%99%EC%A7%A4%EB%B0%A9/cpjmmjoehdjkicbaiikanabgecjbdoko)

**Comment by green1052** [comment]
https://github.com/green1052/DCSelfImage
