### ISSUE TITLE
글 미리보기 창 댓글 삭제 메시지는 버그인가요 ?

### ISSUE THREAD

**Issue by coffeechococake7** [green1052/DCRefresher-Reborn#80]
원래 게시글 작성자는 댓글 지울 수 있는데
미리보기 창에서는 본인 댓글 아니라고 안 지워지더라구요
이 부분 인지하고 계시는지

**Comment by green1052** [comment]
![eb6eb6583cadf161eac8832f3c1997a564b05785ae3c4d98a0149f83783330e1](https://github.com/green1052/DCRefresher-Reborn/assets/34261355/6fb7d493-d28d-4230-a032-11a2be2bc486)

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/commit/1bcac5d2589207653fa42668932396a6a4c5f659
