### ISSUE TITLE
나가기 방지 작동 버그 ?

### ISSUE THREAD

**Issue by coffeechococake7** [green1052/DCRefresher-Reborn#83]
글을 다 쓰고 나서 등록 버튼을 눌렀을 때도 나가기 방지 기능이 작동되는데

정상적인 작동 맞나요 ?

**Comment by coffeechococake7** [comment]
@green1052 그리고 더 중요한 것이 이게 다른 커뮤니티 (제가 확인한 바로는 아카라이브 글 작성 창) 에서도 작동하는 것으로 의심됩니다

**Comment by green1052** [comment]
https://github.com/green1052/DCRefresher-Reborn/blob/5e18f9fef0786c6256f1e0069ffb3583724c2d74/src/manifest_v3.json#L10
