### ISSUE TITLE
내용 최대 몇자 버그 개선

### ISSUE THREAD

**Issue by coffeechococake7** [green1052/DCRefresher-Reborn#88]
주로 복붙 시에 내용 최대 65 535자 이하 여야 합니다 뜨는 버그
개선 가능하시나요 붙여넣기 한게 내용 글자 몇자 쓴것보다 많다는게
일반인은 이해가 되지 않습니다

**Comment by green1052** [comment]
![17d28069828d6b82](https://github.com/green1052/DCRefresher-Reborn/assets/34261355/05ece1b8-41bd-420d-9a55-8985749547cf)

**Comment by green1052** [comment]
요청이 너무 많아서 정리하기 힘들어서 그런데
디스코드에 정리해서 올려주실 수 있나요?

**Comment by hotspa6** [comment]
> 요청이 너무 많아서 정리하기 힘들어서 그런데 디스코드에 정리해서 올려주실 수 있나요?

@hotspa6 디스코드 밴 당한 걸로 확인돼 있어서 디코를 못 들어갈 것 같습니다만

**Comment by coffeechococake7** [comment]
> 요청이 너무 많아서 정리하기 힘들어서 그런데 디스코드에 정리해서 올려주실 수 있나요?

@green1052 디스코드 밴 당한 걸로 확인돼 있어서 디코를 못 들어갈 것 같습니다만
