### ISSUE TITLE
주딱 파딱 표기오류문제

### ISSUE THREAD

**Issue by emptycan1010** [green1052/DCRefresher-Reborn#9]
![image](https://user-images.githubusercontent.com/85441644/209962581-042cfb6a-eb7d-486c-b960-14337006920f.png)
![image](https://user-images.githubusercontent.com/85441644/209962598-0522ac9f-d097-434f-8f83-0178d98d49e3.png)
파딱을 주딱으로 표기합니다.

**Comment by green1052** [comment]
수정됐습니다.

**Comment by green1052** [comment]
[3.6.2](https://github.com/green1052/DCRefresher-Reborn/releases/tag/3.6.2) 릴리즈에 반영됐습니다.
